// Code generated by goctl. DO NOT EDIT.
// Source: stock.proto

package server

import (
	"context"

	"zero-dt/order/app/stock/rpc/internal/logic"
	"zero-dt/order/app/stock/rpc/internal/svc"
	"zero-dt/order/app/stock/rpc/pb"
)

type StockServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedStockServer
}

func NewStockServer(svcCtx *svc.ServiceContext) *StockServer {
	return &StockServer{
		svcCtx: svcCtx,
	}
}

func (s *StockServer) Deduct(ctx context.Context, in *pb.DeductReq) (*pb.DeductResp, error) {
	l := logic.NewDeductLogic(ctx, s.svcCtx)
	return l.Deduct(in)
}

func (s *StockServer) DeductRollback(ctx context.Context, in *pb.DeductReq) (*pb.DeductResp, error) {
	l := logic.NewDeductRollbackLogic(ctx, s.svcCtx)
	return l.DeductRollback(in)
}
